config/routes.rb
Rails.application.routes.draw do
  resources :numbers

end

app/models/number.rb
class Number < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_action :set_number, only: [:show, :edit, :update, :destroy]

  # GET /numbers
  # GET /numbers.json
  def index
    @numbers = Number.all
  end

  # GET /numbers/1
  # GET /numbers/1.json
  def show
  end

  # GET /numbers/new
  def new
    @number = Number.new
  end

  # GET /numbers/1/edit
  def edit
  end

  # POST /numbers
  # POST /numbers.json
  def create
    @number = Number.new(number_params)

    respond_to do |format|
      if @number.save
        format.html { redirect_to @number, notice: 'Number was successfully created.' }
        format.json { render :show, status: :created, location: @number }
      else
        format.html { render :new }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /numbers/1
  # PATCH/PUT /numbers/1.json
  def update
    respond_to do |format|
      if @number.update(number_params)
        format.html { redirect_to @number, notice: 'Number was successfully updated.' }
        format.json { render :show, status: :ok, location: @number }
      else
        format.html { render :edit }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /numbers/1
  # DELETE /numbers/1.json
  def destroy
    @number.destroy
    respond_to do |format|
      format.html { redirect_to numbers_url, notice: 'Number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number
      @number = Number.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def number_params
      params.require(:number).permit(:number, :description, :user, :when)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pythagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/numbers/_form.html.erb
<%= form_for(@number) do |f| %>
  <% if @number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@number.errors.count, "error") %> prohibited this number from being saved:</h2>

      <ul>
      <% @number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
   <div class="description">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :when %><br>
    <%= f.date_select :when %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/numbers/edit.html.erb
<h1>Editing number</h1>

<%= render 'form' %>

<%= link_to 'Show', @number %> |
<%= link_to 'Back', numbers_path %>

app/views/numbers/index.html.erb
<center>
<br>
<br>
<h2>Pythagram</h2>
<h3>Your world in numbers.</h3>
<br>
<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Description</th>
      <th>User</th>
      <th>When</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @numbers.each do |number| %>
      <tr>
        <td><h1><%= number.number %></h1></td>
        <td><%= number.description %></td>
        <td><%= number.user %></td>
        <td><%= number.when %></td>
        <td><%= link_to 'Show', number %></td>
        <td><%= link_to 'Edit', edit_number_path(number) %></td>
        <td><%= link_to 'Destroy', number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Number', new_number_path %>
</center>

app/views/numbers/new.html.erb
<h1>New number</h1>

<%= render 'form' %>

<%= link_to 'Back', numbers_path %>

app/views/numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @number.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @number.user %>
</p>

<p>
  <strong>When:</strong>
  <%= @number.when %>
</p>

<%= link_to 'Edit', edit_number_path(@number) %> |
<%= link_to 'Back', numbers_path %>